apiVersion: apps/v1
kind: Deployment
metadata:
  name: teste-felipe
spec:
  replicas: 1
  progressDeadlineSeconds: 120
  selector:
    matchLabels:
      app: teste-felipe
  template:
    metadata:
      labels:
        app: teste-felipe
    spec:
      containers:
      - name: teste-felipe
        image: 773571409125.dkr.ecr.us-east-1.amazonaws.com/teste-felipe:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: teste-felipe
spec:
  type: NodePort
  selector:
    app: teste-felipe
  ports:
    - port: 3000
      nodePort: 30000

