apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-api
  template:
    metadata:
      labels:
        app: sre-api
    spec:
      containers:
      - name: sre-api
        image: 773571409125.dkr.ecr.us-east-1.amazonaws.com/teste-felipe:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sre-api
spec:
  type: NodePort
  selector:
    app: sre-api
  ports:
    - port: 3000
      nodePort: 30000

