apiVersion: apps/v1
kind: Deployment
metadata:
  name: teste-felipe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teste-felipe
  template:
    metadata:
      labels:
        app: teste-felipe
    spec:
      containers:
      - name: teste-felipe
        image: 773571409125.dkr.ecr.us-east-1.amazonaws.com/teste-felipe:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: teste-felipe
spec:
  type: NodePort
  selector:
    app: teste-felipe
  ports:
    - port: 3000
      nodePort: 30000

