apiVersion: v1
kind: Service
metadata:
  name: teste-felipe
spec:
  type: NodePort
  selector:
    app: teste-felipe
  ports:
    - port: 3000        # porta interna do container
      targetPort: 3000  # corresponde ao containerPort no Deployment
      nodePort: 30000   # porta no nรณ EC2

