name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
            | docker login --username AWS --password-stdin 773571409125.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t teste-felipe:${{ github.sha }} .

      - name: Tag and push to ECR
        run: |
          docker tag teste-felipe:${{ github.sha }} 773571409125.dkr.ecr.us-east-1.amazonaws.com/teste-felipe:${{ github.sha }}
          docker push 773571409125.dkr.ecr.us-east-1.amazonaws.com/teste-felipe:${{ github.sha }}
          # Empurra também o latest
          docker tag teste-felipe:${{ github.sha }} 773571409125.dkr.ecr.us-east-1.amazonaws.com/teste-felipe:latest
          docker push 773571409125.dkr.ecr.us-east-1.amazonaws.com/teste-felipe:latest
  deploy-to-k8s:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl && sudo mv kubectl /usr/local/bin/

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy manifest
        run: |
          ssh -o StrictHostKeyChecking=no root@44.202.48.164 << 'EOF'
            # 1) Recria o secret com token válido
            PASSWORD=\$(aws ecr get-login-password --region us-east-1)
            kubectl create secret docker-registry ecr-registry \
              --docker-server=773571409125.dkr.ecr.us-east-1.amazonaws.com \
              --docker-username=AWS \
              --docker-password="\$PASSWORD" \
              --dry-run=client -o yaml | kubectl apply -f -

            # Primeiro cria (ou atualiza) o deployment/service
            kubectl apply -f /root/projeto/k8s-manifest.yaml
            # Depois ajusta a imagem (evita recriar tudo caso só mudem tags)
            kubectl set image deployment/teste-felipe teste-felipe=773571409125.dkr.ecr.us-east-1.amazonaws.com/teste-felipe:${{ github.sha }}
            kubectl rollout status deployment/teste-felipe 
          EOF
